version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: weather_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 10s
      retries: 10

  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=weather_mysql;Port=3306;Database=db;User=user;Password=password;
    depends_on:
      mysql-db:
        condition: service_healthy

  sdk-tools:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: weather_sdk_tools
    volumes:
      - .:/src
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Port=3306;Database=db;User=user;Password=password;
    depends_on:
      - mysql-db
volumes:
  mysql_data: